### Linux Init ###
---
- hosts: 127.0.0.1
  connection: local
  tasks:

# APT installs

  - name: Install apt packages
    apt:
      pkg:
        - vim
        - apt-transport-https
        - curl
        - zsh
        - python-is-python3
        - python3-pip
        - snapd
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - virtualbox
        - ffmpeg
        - python3.9-venv
      state: latest
      state: present
      update_cache: true

  - name: Install Pip3
      ansible.builtin.command: python3 -m ensurepip --upgrade

  - name: download and place gpg key for brave    

